/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio_archivos;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeffrey Felix
 */
public class Agregar_Mascota extends javax.swing.JFrame {

    int cedulaDueño = Cliente.Cedula();

    public Agregar_Mascota() {
        initComponents();
        txtCedulaDueño.setText(Integer.toString(cedulaDueño));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lolo = new javax.swing.JLabel();
        txtColorPerro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRazaPerro = new javax.swing.JTextField();
        txtNombrePerro = new javax.swing.JTextField();
        txtCedulaDueño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregarMascota = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        JCFechaN = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lolo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lolo.setText("Datos de mascota");
        getContentPane().add(lolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 13, -1, -1));
        getContentPane().add(txtColorPerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 189, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel7.setText("Nombre del perro:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(txtRazaPerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 189, -1));
        getContentPane().add(txtNombrePerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 189, -1));

        txtCedulaDueño.setEditable(false);
        getContentPane().add(txtCedulaDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 189, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel8.setText("Raza del perro:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel10.setText("Color del perro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel11.setText("Cedula de dueño:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnAgregarMascota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarMascota.setText("Agregar");
        btnAgregarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 291, 185, 58));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel12.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButton3.setText("←");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));
        getContentPane().add(JCFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 189, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MascotaNueva.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 250, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoBlanco.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMascotaActionPerformed
        boolean cerrar = false;
        if (txtNombrePerro.getText().equals("") || txtRazaPerro.getText().equals("") || txtColorPerro.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe rellenar todos los campos");
        } else {
            File x = new File("C:\\Veterinaria_PerrosPET");
            String Dir = "C:\\Veterinaria_PerrosPET";
            File mascotas = new File(Dir, "Mascotas.txt");
            FileWriter fw = null;
            if (!mascotas.exists()) { //No existe el archivo
                x.mkdir();
                try {
                    mascotas.createNewFile();
                } catch (IOException ex) {
                    System.out.println("Error");
                }
            }
            String dia = "";
            String mes = "";
            String año = "";
            try {
                fw = new FileWriter(mascotas, true);
                PrintWriter pw = new PrintWriter(fw);
                String fechaNacimiento = "";
                int cedulaDueño = Integer.parseInt(txtCedulaDueño.getText());
                String nombrePerro = txtNombrePerro.getText();
                String razaPerro = txtRazaPerro.getText();
                String colorPerro = txtColorPerro.getText();
                try {
                    dia = Integer.toString(JCFechaN.getCalendar().get(Calendar.DAY_OF_MONTH));
                    mes = Integer.toString(JCFechaN.getCalendar().get(Calendar.MONTH)+1);
                    año = Integer.toString(JCFechaN.getCalendar().get(Calendar.YEAR));
                    fechaNacimiento = dia + "/" + mes + "/" + año;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Debe elegir una fecha");
                }
                if (!"".equals(fechaNacimiento)) {
                    int diaActual = LocalDate.now().getDayOfMonth();
                    int mesActual = LocalDate.now().getMonthValue();
                    int AAActual = LocalDate.now().getYear();
                    if (Integer.parseInt(año) < AAActual) {
                        pw.print(cedulaDueño + ";" + nombrePerro + ";" + razaPerro + ";" + colorPerro + ";" + fechaNacimiento + ";");
                        pw.println();
                        JOptionPane.showMessageDialog(rootPane, "La mascota se guardo correctamente");
                        txtCedulaDueño.setText("");
                        txtNombrePerro.setText("");
                        txtRazaPerro.setText("");
                        txtColorPerro.setText("");
                        cerrar = true;
                    } else {
                        if (Integer.parseInt(mes) < mesActual) {
                            pw.print(cedulaDueño + ";" + nombrePerro + ";" + razaPerro + ";" + colorPerro + ";" + fechaNacimiento + ";");
                            pw.println();
                            JOptionPane.showMessageDialog(rootPane, "La mascota se guardo correctamente");
                            txtCedulaDueño.setText("");
                            txtNombrePerro.setText("");
                            txtRazaPerro.setText("");
                            txtColorPerro.setText("");
                            cerrar = true;
                        } else if (Integer.parseInt(dia) <= diaActual) {
                            pw.print(cedulaDueño + ";" + nombrePerro + ";" + razaPerro + ";" + colorPerro + ";" + fechaNacimiento + ";");
                            pw.println();
                            JOptionPane.showMessageDialog(rootPane, "La mascota se guardo correctamente");
                            txtCedulaDueño.setText("");
                            txtNombrePerro.setText("");
                            txtRazaPerro.setText("");
                            txtColorPerro.setText("");
                            cerrar = true;
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Fecha invalida");
                        }
                    }

                }
            } catch (IOException e) {
                System.out.println(e);
            } finally {
                try {
                    if (fw != null) {
                        fw.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
            if (cerrar == true) {
                cerrar = false;
                dispose();
            }
        }


    }//GEN-LAST:event_btnAgregarMascotaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Mascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JCFechaN;
    private javax.swing.JButton btnAgregarMascota;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lolo;
    private javax.swing.JTextField txtCedulaDueño;
    private javax.swing.JTextField txtColorPerro;
    private javax.swing.JTextField txtNombrePerro;
    private javax.swing.JTextField txtRazaPerro;
    // End of variables declaration//GEN-END:variables
}
