/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio_archivos;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey Felix
 */
public class Agregar_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Cliente
     */
    public Agregar_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lolo = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono_AC = new javax.swing.JTextField();
        txtNombre_AC = new javax.swing.JTextField();
        txtCedula_AC = new javax.swing.JTextField();
        txtCorreo_AC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Direccion:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cedula:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Correo:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 185, 58));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel8.setText("Telefono:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel10.setText("Direccion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel11.setText("Cedula:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel12.setText("Correo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lolo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lolo.setText("Datos personales");
        getContentPane().add(lolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 26, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 187, -1));
        getContentPane().add(txtTelefono_AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 189, -1));
        getContentPane().add(txtNombre_AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 190, -1));
        getContentPane().add(txtCedula_AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 190, -1));
        getContentPane().add(txtCorreo_AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 187, -1));

        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/humano.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 200, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoBlanco.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (txtCedula_AC.getText().equals("") || txtNombre_AC.getText().equals("") || txtTelefono_AC.getText().equals("") || txtDireccion.getText().equals("") || txtCorreo_AC.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe rellenar todos los campos");
        } else {
            File x = new File("C:\\Veterinaria_PerrosPET");
            String Dir = "C:\\Veterinaria_PerrosPET";
            File Clientes = new File(Dir, "Clientes.txt");
            FileWriter fw = null;
            if (!Clientes.exists()) { //No existe el archivo
                x.mkdir();
                try {
                    Clientes.createNewFile();
                } catch (IOException ex) {
                    System.out.println("Error");
                }
            }
            try {
                fw = new FileWriter(Clientes, true);
                PrintWriter pw = new PrintWriter(fw);
                int cedula = 0;
                int telefono = 0;
                try {
                    cedula = Integer.parseInt(txtCedula_AC.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Debe rellenar la cedula solo con numeros");
                }
                String nombre = txtNombre_AC.getText();
                try {
                    telefono = Integer.parseInt(txtTelefono_AC.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Debe rellenar el telefono solo con numeros");
                }
                String direccion = txtDireccion.getText();
                String correo = txtCorreo_AC.getText();
                if (cedula != 0 && telefono != 0) {
                    pw.print(cedula + ";" + nombre + ";" + telefono + ";" + direccion + ";" + correo + ";");
                    pw.println();
                    JOptionPane.showMessageDialog(rootPane, "El archivo se guardo");
                    txtCedula_AC.setText("");
                    txtNombre_AC.setText("");
                    txtTelefono_AC.setText("");
                    txtDireccion.setText("");
                    txtCorreo_AC.setText("");
                    Cliente pantalla_Cliente = new Cliente();
                    pantalla_Cliente.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se pudo guardar el archivo");
                    Menu pantalla_1 = new Menu();
                    pantalla_1.setVisible(true);
                }
            } catch (IOException e) {
                System.out.println(e);
            } finally {
                try {
                    if (fw != null) {
                        fw.close();
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }

            }
            dispose();

        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente pantalla_Cliente = new Cliente();
        pantalla_Cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lolo;
    private javax.swing.JTextField txtCedula_AC;
    private javax.swing.JTextField txtCorreo_AC;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre_AC;
    private javax.swing.JTextField txtTelefono_AC;
    // End of variables declaration//GEN-END:variables
}
